//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace May
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sotrudnik()
        {
            this.ZaiavkaNeispravnost = new HashSet<ZaiavkaNeispravnost>();
        }
    
        public int id { get; set; }
        public string fio { get; set; }
        public string phone { get; set; }
        public Nullable<int> doljnost_id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> roles_id { get; set; }
    
        public virtual Doljnost Doljnost { get; set; }
        public virtual Roles Roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZaiavkaNeispravnost> ZaiavkaNeispravnost { get; set; }
    }
}
