//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace May
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZaiavkaNeispravnost
    {
        public int id { get; set; }
        public Nullable<System.DateTime> datedob { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> neispravost_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> sotrudnik_id { get; set; }
        public string opisanie { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Sotrudnik Sotrudnik { get; set; }
        public virtual StatusZaiavka StatusZaiavka { get; set; }
        public virtual TypeNeispravnost TypeNeispravnost { get; set; }
    }
}
